// AUTO-GENERATED by `supabase gen types typescript --project-id <ref> --schema public`.
// After applying db/schema.sql to your Supabase project, regenerate this file:
//   pnpm db:types
//
// The content below is a hand-written placeholder so the rest of the repo type-checks
// before the first generation. Once you run `pnpm db:types`, this file is overwritten.

export type Json = string | number | boolean | null | { [k: string]: Json } | Json[];

export type Database = {
  public: {
    Tables: {
      resources: {
        Row: {
          id: string;
          user_id: string;
          url: string;
          content: string;
          status: 'pending' | 'consumed';
          created_at: string;
          consumed_at: string | null;
        };
        Insert: {
          id?: string;
          user_id?: string;
          url: string;
          content: string;
          status?: 'pending' | 'consumed';
          created_at?: string;
          consumed_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          url?: string;
          content?: string;
          status?: 'pending' | 'consumed';
          created_at?: string;
          consumed_at?: string | null;
        };
        Relationships: [];
      };
      settings: {
        Row: {
          user_id: string;
          tone_prompt: string;
          resources_per_newsletter: number;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          tone_prompt?: string;
          resources_per_newsletter?: number;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          tone_prompt?: string;
          resources_per_newsletter?: number;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};
